const menu=document.querySelector('.menu');const nav=document.querySelector('#nav');
menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open);menu.textContent=open?'×':'☰';menu.setAttribute('aria-label',open?'Close navigation':'Open navigation')});
nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent='☰';menu.setAttribute('aria-label','Open navigation')}));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav?.classList.contains('open')){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent='☰';menu.setAttribute('aria-label','Open navigation');menu.focus()}});
document.querySelector('#contact-form')?.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.currentTarget);const fields=[['Contact person','name'],['Business name','business'],['Contact number','phone'],['Email','email'],['Workflow to automate','message']];const body=fields.map(([label,key])=>`${label}: ${data.get(key)||'Not provided'}`).join('\n');window.location.href=`mailto:fatmah@utana.group?subject=${encodeURIComponent('Early automation pilot application')}&body=${encodeURIComponent(body)}`;document.querySelector('#form-status').textContent='Your email app should open with your application. Review and send it to complete your enquiry. If it does not open, email fatmah@utana.group directly.'});

// Decorative motion follows the document without intercepting scrolling.
(()=>{const reduced=matchMedia('(prefers-reduced-motion: reduce)');const canvas=document.createElement('canvas');canvas.id='workflow-background';canvas.setAttribute('aria-hidden','true');document.body.prepend(canvas);const ctx=canvas.getContext('2d');if(!ctx)return;let width=0,height=0,frame=0,active=true;const resize=()=>{width=innerWidth;height=innerHeight;const dpr=Math.min(devicePixelRatio||1,1.5);canvas.width=width*dpr;canvas.height=height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)};resize();addEventListener('resize',resize,{passive:true});const art=document.querySelector('.orbit-art');function paint(time){ctx.clearRect(0,0,width,height);const travel=reduced.matches?0:scrollY*.0005;const tick=reduced.matches?0:time*.00022;for(let row=0;row<7;row++){ctx.beginPath();for(let x=0;x<=width+20;x+=20){const y=height*.45+row*48+Math.sin(x/width*5+tick+travel+row*.23)*90; x===0?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.strokeStyle='rgba(158,186,223,'+(0.10+row*.014)+')';ctx.lineWidth=1.2;ctx.stroke();const px=((tick*.13+row*.147+travel*.1)%1)*width;const py=height*.45+row*48+Math.sin(px/width*5+tick+travel+row*.23)*90;ctx.beginPath();ctx.arc(px,py,3,0,Math.PI*2);ctx.fillStyle='rgba(211,227,248,.8)';ctx.fill()}if(art&&!reduced.matches){art.style.setProperty('--orbit-shift',Math.min(scrollY*.16,160)+'px');art.style.setProperty('--orbit-turn',Math.min(scrollY*.025,35)+'deg')}if(active&&!reduced.matches)frame=requestAnimationFrame(paint)}function start(){cancelAnimationFrame(frame);paint(performance.now())}document.addEventListener('visibilitychange',()=>{active=!document.hidden;if(active)start();else cancelAnimationFrame(frame)});reduced.addEventListener('change',start);addEventListener('resize',()=>{if(reduced.matches)start()},{passive:true});start();if(!reduced.matches&&'IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.section-heading,.services article,.team-member,.post,.uc-card,.uc-block').forEach(el=>{el.classList.add('reveal-ready');observer.observe(el)})}})();

(()=>{const source=document.querySelector('#shape-background')||document.querySelector('#workflow-background');let overlays=[];function setup(){document.querySelectorAll('.light,.contact').forEach(section=>{const overlay=document.createElement('canvas');overlay.className='section-motion';overlay.setAttribute('aria-hidden','true');section.prepend(overlay);overlays.push([section,overlay])})}setup();let last=0;function paint(t){if(t-last>40){last=t;const src=document.querySelector('#shape-background')||document.querySelector('#workflow-background');if(src){for(const [section,c] of overlays){const r=section.getBoundingClientRect();if(r.bottom<0||r.top>innerHeight)continue;const width=Math.round(r.width),height=Math.round(Math.min(r.height,innerHeight));if(c.width!==width||c.height!==height){c.width=width;c.height=height}c.style.top=Math.max(0,-r.top)+'px';const ctx=c.getContext('2d');ctx.clearRect(0,0,width,height);ctx.drawImage(src,0,Math.max(0,r.top)*src.height/innerHeight,src.width,height*src.height/innerHeight,0,0,width,height);ctx.globalCompositeOperation='source-in';ctx.fillStyle='#345276';ctx.fillRect(0,0,width,height);ctx.globalCompositeOperation='source-over'}}}requestAnimationFrame(paint)}requestAnimationFrame(paint)})();
