const menu=document.querySelector('.menu');const nav=document.querySelector('#nav');const mobileNavigation=matchMedia('(max-width:1100px)');
const setMenuOpen=(open,{moveFocus=false,restoreFocus=false}={})=>{if(!menu||!nav)return;const mobile=mobileNavigation.matches;open=mobile&&open;menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open);nav.inert=mobile&&!open;menu.textContent=open?'×':'☰';menu.setAttribute('aria-label',open?'Close navigation':'Open navigation');if(open&&moveFocus)nav.querySelector('a')?.focus();if(!open&&restoreFocus&&mobile)menu.focus()};
const syncMenuMode=()=>{if(!menu||!nav)return;const restoreFocus=mobileNavigation.matches&&nav.contains(document.activeElement);setMenuOpen(false,{restoreFocus})};
menu?.addEventListener('click',event=>{const open=menu.getAttribute('aria-expanded')!=='true';setMenuOpen(open,{moveFocus:open&&(event.detail===0||menu.matches(':focus-visible')),restoreFocus:!open})});
nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',event=>{const keyboard=event.detail===0;setMenuOpen(false);if(keyboard)requestAnimationFrame(()=>menu.focus({preventScroll:true}))}));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav?.classList.contains('open'))setMenuOpen(false,{restoreFocus:true})});
mobileNavigation.addEventListener('change',syncMenuMode);syncMenuMode();

document.querySelector('#contact-form')?.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget);const fields=[['Contact person','name'],['Business name','business'],['Contact number','phone'],['Email','email'],['Workflow to automate','message']];const body=fields.map(([label,key])=>`${label}: ${data.get(key)||'Not provided'}`).join('\n');window.location.href=`mailto:sapiens@utana.group?subject=${encodeURIComponent('Early automation pilot application')}&body=${encodeURIComponent(body)}`;document.querySelector('#form-status').textContent='Your email app should open with your application. Review and send it to complete your enquiry. If it does not open, email sapiens@utana.group directly.'});

// Reveal content independently from the optional decorative canvas.
(()=>{const reduced=matchMedia('(prefers-reduced-motion: reduce)');if(reduced.matches||!('IntersectionObserver' in window))return;const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.section-heading,.services article,.team-member,.post,.uc-card,.uc-block').forEach(el=>{el.classList.add('reveal-ready');observer.observe(el)})})();

// Decorative motion is only created for landing pages that include a hero.
(()=>{if(!document.querySelector('.hero')||document.body.dataset.shape)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)');const compact=matchMedia('(max-width:760px)');const saveData=navigator.connection?.saveData===true;document.body.classList.toggle('save-data',saveData);const canvas=document.createElement('canvas');canvas.id='workflow-background';canvas.setAttribute('aria-hidden','true');document.body.prepend(canvas);const ctx=canvas.getContext('2d');if(!ctx){canvas.remove();return}let width=0,height=0,frame=0,lastPaint=0,active=!document.hidden;const staticMotion=()=>reduced.matches||saveData;const updateMode=()=>{canvas.dataset.animationMode=staticMotion()?'static':compact.matches?'limited':'full'};const resize=()=>{width=innerWidth;height=innerHeight;const dpr=Math.min(devicePixelRatio||1,compact.matches||saveData?1:1.5);canvas.width=width*dpr;canvas.height=height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);updateMode()};const art=document.querySelector('.orbit-art');function paint(time){if(!staticMotion()&&compact.matches&&time-lastPaint<1000/30){frame=requestAnimationFrame(paint);return}lastPaint=time;ctx.clearRect(0,0,width,height);const travel=staticMotion()?0:scrollY*.0005;const tick=staticMotion()?0:time*.00022;for(let row=0;row<7;row++){ctx.beginPath();for(let x=0;x<=width+20;x+=20){const y=height*.45+row*48+Math.sin(x/width*5+tick+travel+row*.23)*90;x===0?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.strokeStyle='rgba(158,186,223,'+(0.10+row*.014)+')';ctx.lineWidth=1.2;ctx.stroke();const px=((tick*.13+row*.147+travel*.1)%1)*width;const py=height*.45+row*48+Math.sin(px/width*5+tick+travel+row*.23)*90;ctx.beginPath();ctx.arc(px,py,3,0,Math.PI*2);ctx.fillStyle='rgba(211,227,248,.8)';ctx.fill()}if(art&&!staticMotion()){art.style.setProperty('--orbit-shift',Math.min(scrollY*.16,160)+'px');art.style.setProperty('--orbit-turn',Math.min(scrollY*.025,35)+'deg')}if(active&&!staticMotion())frame=requestAnimationFrame(paint)}function start(){cancelAnimationFrame(frame);lastPaint=0;updateMode();if(active)paint(performance.now())}resize();addEventListener('resize',()=>{resize();if(staticMotion())start()},{passive:true});document.addEventListener('visibilitychange',()=>{active=!document.hidden;if(active)start();else cancelAnimationFrame(frame)});reduced.addEventListener('change',start);compact.addEventListener('change',start);start()})();

// Section overlays run only while at least one target section is on screen.
